// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/scheduler.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task_Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskType      int32                  `protobuf:"varint,1,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	DataQuery     string                 `protobuf:"bytes,2,opt,name=data_query,json=dataQuery,proto3" json:"data_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task_Query) Reset() {
	*x = Task_Query{}
	mi := &file_proto_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task_Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Query) ProtoMessage() {}

func (x *Task_Query) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Query.ProtoReflect.Descriptor instead.
func (*Task_Query) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *Task_Query) GetTaskType() int32 {
	if x != nil {
		return x.TaskType
	}
	return 0
}

func (x *Task_Query) GetDataQuery() string {
	if x != nil {
		return x.DataQuery
	}
	return ""
}

type Task_Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task_Reply) Reset() {
	*x = Task_Reply{}
	mi := &file_proto_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Reply) ProtoMessage() {}

func (x *Task_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Reply.ProtoReflect.Descriptor instead.
func (*Task_Reply) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *Task_Reply) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type NodeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodesPort     []int32                `protobuf:"varint,1,rep,packed,name=nodes_port,json=nodesPort,proto3" json:"nodes_port,omitempty"`
	LeaderPort    int32                  `protobuf:"varint,2,opt,name=leader_port,json=leaderPort,proto3" json:"leader_port,omitempty"`
	ClientPort    int32                  `protobuf:"varint,3,opt,name=client_port,json=clientPort,proto3" json:"client_port,omitempty"`
	TaskId        int32                  `protobuf:"varint,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeList) Reset() {
	*x = NodeList{}
	mi := &file_proto_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeList) ProtoMessage() {}

func (x *NodeList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeList.ProtoReflect.Descriptor instead.
func (*NodeList) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *NodeList) GetNodesPort() []int32 {
	if x != nil {
		return x.NodesPort
	}
	return nil
}

func (x *NodeList) GetLeaderPort() int32 {
	if x != nil {
		return x.LeaderPort
	}
	return 0
}

func (x *NodeList) GetClientPort() int32 {
	if x != nil {
		return x.ClientPort
	}
	return 0
}

func (x *NodeList) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type RequestVoteArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   int32                  `protobuf:"varint,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteArgs) Reset() {
	*x = RequestVoteArgs{}
	mi := &file_proto_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteArgs) ProtoMessage() {}

func (x *RequestVoteArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteArgs.ProtoReflect.Descriptor instead.
func (*RequestVoteArgs) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *RequestVoteArgs) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteArgs) GetCandidateId() int32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

type RequestVoteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteReply) Reset() {
	*x = RequestVoteReply{}
	mi := &file_proto_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteReply) ProtoMessage() {}

func (x *RequestVoteReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteReply.ProtoReflect.Descriptor instead.
func (*RequestVoteReply) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *RequestVoteReply) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteReply) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{5}
}

type ServerPort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPort) Reset() {
	*x = ServerPort{}
	mi := &file_proto_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPort) ProtoMessage() {}

func (x *ServerPort) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPort.ProtoReflect.Descriptor instead.
func (*ServerPort) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *ServerPort) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RaftServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	IsVoter       bool                   `protobuf:"varint,3,opt,name=is_voter,json=isVoter,proto3" json:"is_voter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftServer) Reset() {
	*x = RaftServer{}
	mi := &file_proto_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftServer) ProtoMessage() {}

func (x *RaftServer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftServer.ProtoReflect.Descriptor instead.
func (*RaftServer) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *RaftServer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RaftServer) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RaftServer) GetIsVoter() bool {
	if x != nil {
		return x.IsVoter
	}
	return false
}

type RaftConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*RaftServer          `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftConfiguration) Reset() {
	*x = RaftConfiguration{}
	mi := &file_proto_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftConfiguration) ProtoMessage() {}

func (x *RaftConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftConfiguration.ProtoReflect.Descriptor instead.
func (*RaftConfiguration) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *RaftConfiguration) GetServers() []*RaftServer {
	if x != nil {
		return x.Servers
	}
	return nil
}

type AddVoterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVoterRequest) Reset() {
	*x = AddVoterRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVoterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVoterRequest) ProtoMessage() {}

func (x *AddVoterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVoterRequest.ProtoReflect.Descriptor instead.
func (*AddVoterRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *AddVoterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddVoterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_proto_scheduler_proto protoreflect.FileDescriptor

const file_proto_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x15proto/scheduler.proto\x12\tscheduler\"H\n" +
	"\n" +
	"Task_Query\x12\x1b\n" +
	"\ttask_type\x18\x01 \x01(\x05R\btaskType\x12\x1d\n" +
	"\n" +
	"data_query\x18\x02 \x01(\tR\tdataQuery\"%\n" +
	"\n" +
	"Task_Reply\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\"\x84\x01\n" +
	"\bNodeList\x12\x1d\n" +
	"\n" +
	"nodes_port\x18\x01 \x03(\x05R\tnodesPort\x12\x1f\n" +
	"\vleader_port\x18\x02 \x01(\x05R\n" +
	"leaderPort\x12\x1f\n" +
	"\vclient_port\x18\x03 \x01(\x05R\n" +
	"clientPort\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\x05R\x06taskId\"H\n" +
	"\x0fRequestVoteArgs\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\x05R\vcandidateId\"I\n" +
	"\x10RequestVoteReply\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12!\n" +
	"\fvote_granted\x18\x02 \x01(\bR\vvoteGranted\"\a\n" +
	"\x05Empty\" \n" +
	"\n" +
	"ServerPort\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\"Q\n" +
	"\n" +
	"RaftServer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x19\n" +
	"\bis_voter\x18\x03 \x01(\bR\aisVoter\"D\n" +
	"\x11RaftConfiguration\x12/\n" +
	"\aservers\x18\x01 \x03(\v2\x15.scheduler.RaftServerR\aservers\";\n" +
	"\x0fAddVoterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress2\x80\x02\n" +
	"\n" +
	"LeaderNode\x12:\n" +
	"\rGetServerPort\x12\x10.scheduler.Empty\x1a\x15.scheduler.ServerPort\"\x00\x124\n" +
	"\tHeartbeat\x12\x10.scheduler.Empty\x1a\x13.scheduler.NodeList\"\x00\x12D\n" +
	"\x10GetConfiguration\x12\x10.scheduler.Empty\x1a\x1c.scheduler.RaftConfiguration\"\x00\x12:\n" +
	"\bAddVoter\x12\x1a.scheduler.AddVoterRequest\x1a\x10.scheduler.Empty\"\x002\x87\x01\n" +
	"\n" +
	"ServerNode\x121\n" +
	"\tHeartbeat\x12\x10.scheduler.Empty\x1a\x10.scheduler.Empty\"\x00\x12F\n" +
	"\vRequestVote\x12\x1a.scheduler.RequestVoteArgs\x1a\x1b.scheduler.RequestVoteReply2u\n" +
	"\tScheduler\x12;\n" +
	"\tQueryTask\x12\x15.scheduler.Task_Query\x1a\x15.scheduler.Task_Reply\"\x00\x12+\n" +
	"\x03res\x12\x10.scheduler.Empty\x1a\x10.scheduler.Empty\"\x00B\x1cZ\x1aDistributed_Project-/protob\x06proto3"

var (
	file_proto_scheduler_proto_rawDescOnce sync.Once
	file_proto_scheduler_proto_rawDescData []byte
)

func file_proto_scheduler_proto_rawDescGZIP() []byte {
	file_proto_scheduler_proto_rawDescOnce.Do(func() {
		file_proto_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)))
	})
	return file_proto_scheduler_proto_rawDescData
}

var file_proto_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_scheduler_proto_goTypes = []any{
	(*Task_Query)(nil),        // 0: scheduler.Task_Query
	(*Task_Reply)(nil),        // 1: scheduler.Task_Reply
	(*NodeList)(nil),          // 2: scheduler.NodeList
	(*RequestVoteArgs)(nil),   // 3: scheduler.RequestVoteArgs
	(*RequestVoteReply)(nil),  // 4: scheduler.RequestVoteReply
	(*Empty)(nil),             // 5: scheduler.Empty
	(*ServerPort)(nil),        // 6: scheduler.ServerPort
	(*RaftServer)(nil),        // 7: scheduler.RaftServer
	(*RaftConfiguration)(nil), // 8: scheduler.RaftConfiguration
	(*AddVoterRequest)(nil),   // 9: scheduler.AddVoterRequest
}
var file_proto_scheduler_proto_depIdxs = []int32{
	7, // 0: scheduler.RaftConfiguration.servers:type_name -> scheduler.RaftServer
	5, // 1: scheduler.LeaderNode.GetServerPort:input_type -> scheduler.Empty
	5, // 2: scheduler.LeaderNode.Heartbeat:input_type -> scheduler.Empty
	5, // 3: scheduler.LeaderNode.GetConfiguration:input_type -> scheduler.Empty
	9, // 4: scheduler.LeaderNode.AddVoter:input_type -> scheduler.AddVoterRequest
	5, // 5: scheduler.ServerNode.Heartbeat:input_type -> scheduler.Empty
	3, // 6: scheduler.ServerNode.RequestVote:input_type -> scheduler.RequestVoteArgs
	0, // 7: scheduler.Scheduler.QueryTask:input_type -> scheduler.Task_Query
	5, // 8: scheduler.Scheduler.res:input_type -> scheduler.Empty
	6, // 9: scheduler.LeaderNode.GetServerPort:output_type -> scheduler.ServerPort
	2, // 10: scheduler.LeaderNode.Heartbeat:output_type -> scheduler.NodeList
	8, // 11: scheduler.LeaderNode.GetConfiguration:output_type -> scheduler.RaftConfiguration
	5, // 12: scheduler.LeaderNode.AddVoter:output_type -> scheduler.Empty
	5, // 13: scheduler.ServerNode.Heartbeat:output_type -> scheduler.Empty
	4, // 14: scheduler.ServerNode.RequestVote:output_type -> scheduler.RequestVoteReply
	1, // 15: scheduler.Scheduler.QueryTask:output_type -> scheduler.Task_Reply
	5, // 16: scheduler.Scheduler.res:output_type -> scheduler.Empty
	9, // [9:17] is the sub-list for method output_type
	1, // [1:9] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_scheduler_proto_init() }
func file_proto_scheduler_proto_init() {
	if File_proto_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_scheduler_proto_goTypes,
		DependencyIndexes: file_proto_scheduler_proto_depIdxs,
		MessageInfos:      file_proto_scheduler_proto_msgTypes,
	}.Build()
	File_proto_scheduler_proto = out.File
	file_proto_scheduler_proto_goTypes = nil
	file_proto_scheduler_proto_depIdxs = nil
}
